# Generated by Django 4.0 on 2023-03-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_question_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveydetail',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='surveyquestionsthrough',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='surveyquestionsthrough',
            name='survey_details',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='SurveyDetail',
        ),
        migrations.DeleteModel(
            name='SurveyQuestionsThrough',
        ),
    ]
