# Generated by Django 4.0 on 2023-03-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveydetails',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='surveyquestionsthrough',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='surveyquestionsthrough',
            name='survey_details',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='SurveyDetails',
        ),
        migrations.DeleteModel(
            name='SurveyQuestionsThrough',
        ),
    ]
