# Generated by Django 4.0 on 2023-03-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyQuestionsThrough',
            new_name='SurveyQuestionThrough',
        ),
    ]
