# Generated by Django 4.0 on 2023-03-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_rename_surveyquestionsthrough_surveyquestionthrough'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sort_order',
            field=models.PositiveIntegerField(default=999999999),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating_type',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
