# Generated by Django 4.0 on 2023-03-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_alter_question_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveydetail',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='surveyquestionthrough',
            name='question',
        ),
        migrations.RemoveField(
            model_name='surveyquestionthrough',
            name='survey_detail',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='SurveyDetail',
        ),
        migrations.DeleteModel(
            name='SurveyQuestionThrough',
        ),
    ]
