# Generated by Django 4.0 on 2023-03-07 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0011_remove_surveydetail_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(unique=True)),
                ('rating_type', models.PositiveSmallIntegerField(default=5)),
                ('sort_order', models.PositiveSmallIntegerField(default=9999)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyDetail',
            fields=[
                ('session_id', models.UUIDField(primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_through', to='feedback.question')),
                ('survey_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.surveydetail')),
            ],
        ),
        migrations.AddField(
            model_name='surveydetail',
            name='questions',
            field=models.ManyToManyField(through='feedback.SurveyQuestionThrough', to='feedback.Question'),
        ),
    ]
