# Generated by Django 4.0 on 2023-03-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydetail',
            name='session_id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
