# Generated by Django 4.0 on 2023-03-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_alter_surveydetail_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestionthrough',
            old_name='rating_value',
            new_name='rating',
        ),
    ]
