# Generated by Django 4.0 on 2023-03-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_alter_surveyquestionthrough_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='rating_type',
            new_name='rating_offset',
        ),
    ]
